### ISSUE TITLE
Leaky css class

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-navigation#167]
The placeholder class in navigation is not scoped to anything, so leaks out into the navigation when integrated, resulting in this:

![image](https://cloud.githubusercontent.com/assets/14326547/23166636/ab466798-f841-11e6-9c6d-599c76b79711.png)

We could change one or the other of the clashing placeholder classes, but I would expect CSS in an integrated component to be isolated. Better to wrap your classes in their components.

```scss
sc-navigation {  
  .placeholder {
    ...
  }
}
```

**Comment by dami-gg** [comment]
To be fixed together with #164

**Comment by dami-gg** [comment]
Fixed in #184
