### ISSUE TITLE
BP selector overlap when one business partner

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-navigation#197]
When a user has a single business partner, the disabled selector does not appear correctly:

![image](https://cloud.githubusercontent.com/assets/14326547/23788216/ce7ef6b2-0575-11e7-9cfb-cedd6d83bc09.png)

**Comment by frontendherodk** [comment]
Needs to be discussed with UX

**Comment by frontendherodk** [comment]
I've discussed with UX and we decided to put a max-with on the username and restructure the HTML to be able to have a bit more flexible structure
