### ISSUE TITLE
Why depend on solution-center-login?

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-navigation#199]
Is there any important reason to couple those 2 completely different repos?

Otherwise I'd strongly suggest to decouple those, considering that responsibility of navigation seems to be UI only. Gluing it to authentication (which has zero UI) mixes concerns that are quite far away from each other (and potentially causes all kinds of issues not only integration pains for consumers of the code, but also for those who will maintain those libraries in future - you :).

**Comment by rbarilani** [comment]
I agree on keep the UI as "static" as possible to allow "custom" login (not reccomended but should be possible for flexibility), if that it's already possible don't consider my comment.

**Comment by dami-gg** [comment]
A meeting is already scheduled to discuss this topic in person so I close the ticket
