### ISSUE TITLE
Prefix services names

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/solution-center-navigation#204]
What do you think about prefixing services names?
Why?
In angular1 traditional  we have just one injector and the services are recognized by an identifier that is a string, prefixing the name of services with `scn` might guarantee that you are not overriding or you will not get overriden by other services.

**Comment by dami-gg** [comment]
Yes, I really like that idea and we'll try to address it as soon as possible. 
We also realised when integrating it to our new User Management application...
Thanks for your feedback!
