### ISSUE TITLE
Overlays z-index

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-navigation#223]
In analytics some navigation overlays are not on top of other elements. Possible cause is incorrect `z-index` on containers:

### case 1:
the container `.scn .navigation__sections` has `z-index: 1`
in result `.user-menu` which has `z-index: 500`
but effectively has only `1`, in relation to the container siblings

the same `.dc-btn-dropdown__list` which has `z-index: 900`..

### case 2:
the container `.scn .navigation` has `z-index: 2`
in result even if in `.scn .navigation__sections` you set `z-index: 500`
effectively it has only `2` in relation to the container siblings

**Comment by frontendherodk** [comment]
Closed as part of #220
