### ISSUE TITLE
Navigation overlaps content on mobile

### ISSUE THREAD

**Issue by frontendherodk** [zalando-incubator/solution-center-navigation#260]
The navigation is overlapping the content on mobile meaning that you cannot use some areas of the page
<img width="250" alt="screen shot 2017-05-18 at 11 46 52" src="https://cloud.githubusercontent.com/assets/1649432/26196609/c1c3d4ee-3bbf-11e7-9427-9ef9e9677009.png">

**Comment by cjhowald** [comment]
Taking over from @frontendherodk since he is out.
