### ISSUE TITLE
Global css hiding sc-navigation elements

### ISSUE THREAD

**Issue by ashwinaggarwal** [zalando-incubator/solution-center-navigation#268]
We are using new sc-navigation component, and also loading a few components which need bootstrap for e.g. bootstrap ui datepicker.

Even though we are loading only the minimal bootstrap compiled css for the components we use, it has few global utility classes.

In our case, 'hidden' is hiding the application and product bar in the sc-navigation. See below.

<img width="1267" alt="screen shot 2017-06-09 at 17 46 42 1" src="https://user-images.githubusercontent.com/5618454/26983712-01308968-4d3d-11e7-9ed3-cf7a3b1bb0c3.png">

​
This is because sc-navigation adds class 'hidden' as here in the sc-navigation css and in the html below

<img width="985" alt="screen shot 2017-06-09 at 17 53 50" src="https://user-images.githubusercontent.com/5618454/26983718-061da79e-4d3d-11e7-9d49-d48e6b62040c.png">

​
I personally feel this css should be scoped to the sc-navigation component, something similar to navigation__products--hidden?

**Comment by cjhowald** [comment]
A reasonable request. Indeed, our component styles should be scoped to the component. `hidden` is too common a class name and likely to conflict.

**Comment by frontendherodk** [comment]
@ashwinaggarwal Since we've never used a 3rd party css framework we didn't have this problem yet so thanks for raising the issue. 
We could prefix all of our classes since the css is not scoped to the component.
