### ISSUE TITLE
Some issue with build, #268 persists

### ISSUE THREAD

**Issue by ashwinaggarwal** [zalando-incubator/solution-center-navigation#273]
Hi guys,

With the latest released version, there is some problem with dist package.

Even though the classname was changed in [file](https://github.com/zalando-incubator/solution-center-navigation/blob/master/src/app/navigation.html#L15), it doesn't reflect in the build. Check the screenshot below. So the problem still persists #268 still persists.

<img width="1267" alt="screen shot 2017-06-20 at 11 59 03" src="https://user-images.githubusercontent.com/5618454/27327898-62717202-55b0-11e7-9fd2-4097fe70528d.png">

**Comment by frontendherodk** [comment]
Fixed #270
