### ISSUE TITLE
Verify that all user scenario's are covered

### ISSUE THREAD

**Issue by gregdeane** [zalando-incubator/solution-center-navigation#96]
User with access to **one application** which handles **business partners of a certain type**, who has one available business partner of that type for that application, gets it **automatically selected** and can **access** that application with that business partner.
- e.g.: User1 has access to App1 (which handles brands) and to a business partner BP1 (of type brand). BP1 is automatically selected and the user can use App1 in the context of BP1.

User with access to **one application** which handles **business partners of a certain type**, who has **several available business partners** of that type for that application, can **access all of all them** in the application.
- e.g.: User2 has access to App1 (which handles brands) and to two business partners BP1 and BP2 (both of type brand). He's prompted to choose a business partner and is able to use App1 in the context of both BP1 and BP2 changing as many times as he wants.

User with access to **two applications** which handle **business partners of the same type**, who has **several available business partners** of that type in both, can **navigate** between the applications **keeping the same business partner** without being prompted to select it again.
- e.g.: User3 has access to App1 and App2 (both handle brands) and to a business partner BP1 (of type brand). He selects it BP1 in App1, navigates to App2 and is not automatically prompted to choose another one, keeping the context of BP1 with App2.

User with access to **two applications** which handle **business partners of different type each**, who has **several available business partners of each type** on each correspondent application, can **navigate** between the applications but is **prompted every time** he changes to choose a business partner of the type the new landing application handles.
- e.g.: User4 has access to App1 (which handles brands) and App3 (which handles merchants), to two business partners BP1 and BP2 (both of type brand) in App1 and to two business partners BP3 and BP4 (both of type merchant) in App3. He selects BP1 in App1, navigates to App2 and keeps BP1 selected. Then navigates to App3 and is asked to choose a business partner, showing him BP3 and BP4 as possible options.

**Comment by dami-gg** [comment]
Tested with the demo, but anyway we'll have to revisit this in the future again when real applications start to integrate
